### ISSUE TITLE
write a guide for nirai for windows and mac

### ISSUE THREAD

**Issue by DarthMDev** [nirai-compiler/src#6]
ok a guide will be nice if it is possible to get it working on mac

**Comment by CodeAnGo** [comment]
Working on it as we speak. Windows guide should be up before the night's out.

Yours,

CodeAnGo

**Comment by mghost99** [comment]
Is there a guide available yet? I can get everything BUT panda3d to compile.. It gets stuck at 40% every time i try to compile it. And i'm using VS2010 as suggested in another place since VS2012 wouldn't work.

**Comment by mfwass** [comment]
## Before we begin

Download the following projects linked below and place them in the expected folder structure. If you do not have a folder named _Nirai_, make one somewhere on your computer. I personally have mine on my mac at `/Users/Michael/Nirai/`.

Expected folder structure:

> Nirai/
> [Nirai/panda3d/](https://github.com/nirai-compiler/panda3d)
> [Nirai/panda3d/thirdparty/](https://github.com/nirai-compiler/thirdparty)
> [Nirai/src/](https://github.com/nirai-compiler/src/)
> [Nirai/sample-project/](https://github.com/nirai-compiler/sample-project)
> [Nirai/python/](https://github.com/nirai-compiler/python/)

You will need to have _CMake_ in order to build _Nirai's Python_. You can obtain a copy of _CMake_ via your local OS' package manager (such as _Brew_), or obtain it directly from their website [here](https://cmake.org/download/).

You will also need to change the following commands from `/path/to/*` to your own local computer's path.

## Windows:

```
cd path/to/Nirai/panda3d/
compile.bat
postbuild.bat
cd path/to/src/
aespyd.bat
```

Open up `Nirai/python` and run CMake, then build the project CMake generates.

```
cd path/to/Nirai/sample-project/build/
python -OO make.py -cnm
```

## Mac/Linux

```
cd path/to/Nirai/panda3d/
sh ./compile.sh
sh ./postbuild.sh
cd ../src/
sh ./aespyd.sh
cd ../python/
cmake . && make
cd ../sample-project/build/
python -OO make.py -cnm
```

If you have a conflicting version of _OpenSSL_ installed, you will get a linker error similar to "_invalid architecture for symbols x86_".

I hope this helps. If you have any issues please create another issue.

**Comment by mfwass** [comment]
Added in e80eef3.
